### ISSUE TITLE
CalFire polygons overlap

### ISSUE THREAD

**Issue by peteWT** [peteWT/cec_apl#10]
Tree mortality polygons from CalFire overlap  from different survey years. For our purposes we just want to use the most recent survey -- 2015. This likely results in double counting of trees and may contribute to the extremely large volumes of biomass.

![annual_overlap](https://cloud.githubusercontent.com/assets/2186666/19086870/cda770ec-8a24-11e6-8b11-031917e7d431.png)

@carmentubbesing I'll see if I can fix your `R` code

**Comment by carmentubbesing** [comment]
@peteWT I think we may be on different pages in terms of the meaning of survey year. I thought the word from USFS and CalFire people was that the survey each year only detects **newly dead** trees - ie those that have brown needles that haven't yet fallen. So, combining the polygons additively should theoretically give an accurate picture of the total numbers of dead trees out there, since trees a few years old can be gasified along with the recently dead ones. No?

I guess the potential error with that is that trees can sometimes wait a year or two before dropping their needles. If we're worried about that, we could use polygons from 2013 or 2012 along with 2015 and just get two time stamps.

**Comment by peteWT** [comment]
@carmentubbesing 

> combining the polygons additively should theoretically give an accurate picture of the total numbers of dead trees out there, since trees a few years old can be gasified along with the recently dead ones. No?

That sounds right in theory, however, I am pretty dubious about the ability of the aerial surveyors to detect only mortality that was not surveyed in previous years. I think it would be good to just look at 1 year initially. Esp. in light of the crazy volumes we are trying to sort out.
