### ISSUE TITLE
What does `rxcycle` mean

### ISSUE THREAD

**Issue by peteWT** [peteWT/cec_apl#2]
@ncparker what does `rxcycle` mean is it 20-year increments? if not what is there a time component?

**Comment by ncparker** [comment]
'rxcycle' is when the prescription occurs.  There are four ten-year cycles
in the data.  'rxcycle' should have values of 1-4.  In my work I aggregated
the first two cycles into one big cycle because cycle 1 has more activity
than could be reasonably accomplished and cycle 2 has very little
activity.  Things get more steady in cycles 3 and 4. I think.  I focused on
the first twenty years to match the biorefinery economic life.

**Comment by jd-lara** [comment]
@ncparker How did you aggregate cycles 1 and 2 if they are executed in different locations? I tried to follow your approach but most of the locations for cycle 2 are different from cycle 1.

**Comment by ncparker** [comment]
@jdlara-berkeley I don't think there are any locations with actions in both cycle 1 and cycle 2.  I treated it as one big 20-year cycle where the single action happens sometime within that timeframe.  If there are locations with actions in both cycles then it requires more thought but an average production should work.

**Comment by jd-lara** [comment]
@ncparker so basically is dividing the yield by 20 instead that by 10 and using all the data from both cycles at the same time?

**Comment by ncparker** [comment]
@jdlara-berkeley Yes.
