### ISSUE TITLE
zero.i defined beforehand

### ISSUE THREAD

**Issue by jd-lara** [peteWT/cec_apl#8]
@carmentubbesing There is a small error in parallelization.R code. zero.i is assigned before it is defined. So the count doesn't really work. 

`> inputs = zero.i
Error: object 'zero.i' not found`

**Comment by carmentubbesing** [comment]
You're right. I'll fix that when i get the chance. For now you can either change it to 

`inputs = 1:nrow(drought)`

or you can just skip that whole code chunk  and go straight to line 110, since that whole thing with zeros is just to error check the results; it's not essential.

**Comment by jd-lara** [comment]
I am running it now, for some reason after a couple of hours the CPU usage went down again to 25%. By the way, did you named your results chocolate for a particular reason? 

Jose Daniel Lara
+1 510 502 6238
ca.linkedin.com/pub/jose-daniel-lara/57/7b4/318/

**Comment by carmentubbesing** [comment]
Because I needed to tell them apart from all the many other variables I was using, and because I was craving chocolate. :)

I ran the code for both the original for loop and the parallel code (which uses a foreach loop) for all the polygons within the CR_MORT extent and saved them both to the Box folder. They appear similar but I haven't done a detailed comparison.

**Comment by jd-lara** [comment]
Hi Carmen 

I compared the results from the parallel run and the other code and the CRMOT.csv file is twice as large as the other one and contains more rows. I am trying to upload them both to compare. We need some way of telling where the difference might be. 

Best 

Jose Daniel Lara
+1 510 502 6238
ca.linkedin.com/pub/jose-daniel-lara/57/7b4/318/

**Comment by carmentubbesing** [comment]
Ok, let me know when you've uploaded them
